import { createBookSidebar } from '../../../utils.mts'
  const basePath = '/eastern/esoterica/meihuaishu/'
  const chapterGroups = [
    {
      text: '卷一: 象数易理篇',
      collapsed: true,
      chapters: [
        { slug: 'juan1/01', title: '周易卦象' },
      { slug: 'juan1/02', title: '五行生克' },
      { slug: 'juan1/03', title: '八宫所属五行' },
      { slug: 'juan1/04', title: '卦气旺' },
      { slug: 'juan1/05', title: '卦气衰' },
      { slug: 'juan1/06', title: '十天干' },
      { slug: 'juan1/07', title: '十二地支' },
      { slug: 'juan1/08', title: '八卦象例 (记忆口诀)' },
      { slug: 'juan1/09', title: '占法 (总纲诗)' },
      { slug: 'juan1/10', title: '玩法 (核心思想诗)' },
      { slug: 'juan1/11', title: '卦以八除 (起卦基本规则)' },
      { slug: 'juan1/12', title: '爻以六除 (确定动爻规则)' },
      { slug: 'juan1/13', title: '互卦起例 (分析过程规则)' },
      { slug: 'juan1/14', title: '年月日时起卦' },
      { slug: 'juan1/15', title: '物数占' },
      { slug: 'juan1/16', title: '声音占' },
      { slug: 'juan1/17', title: '字占' },
      { slug: 'juan1/18', title: '一字占至十一字占' },
      { slug: 'juan1/19', title: '丈尺占' },
      { slug: 'juan1/20', title: '尺寸物占' },
      { slug: 'juan1/21', title: '为人占' },
      { slug: 'juan1/22', title: '自己占' },
      { slug: 'juan1/23', title: '占动物' },
      { slug: 'juan1/24', title: '占静物' },
      { slug: 'juan1/25', title: '物卦起例 (端法后天起卦)' },
      { slug: 'juan1/26', title: '八卦万物属类 (并为上卦)' },
      { slug: 'juan1/27', title: '八卦方位图' },
      { slug: 'juan1/28', title: '观梅占 (年月日时占例)' },
      { slug: 'juan1/29', title: '牡丹占' },
      { slug: 'juan1/30', title: '邻夜叩门借物占 (系闻声占例)' },
      { slug: 'juan1/31', title: '今日动静如何 (系声音占例)' },
      { slug: 'juan1/32', title: '西林寺牌额占 (系字画占例)' },
      { slug: 'juan1/33', title: '老人有忧色占 (端法占例)' },
      { slug: 'juan1/34', title: '少年有喜色占' },
      { slug: 'juan1/35', title: '牛哀鸣占' },
      { slug: 'juan1/36', title: '鸡悲鸣占' },
      { slug: 'juan1/37', title: '枯枝坠地占' },
      { slug: 'juan1/38', title: '风觉鸟占' },
      { slug: 'juan1/39', title: '风觉占' },
      { slug: 'juan1/40', title: '鸟占' },
      { slug: 'juan1/41', title: '听声音占' },
      { slug: 'juan1/42', title: '形物占' },
      { slug: 'juan1/43', title: '验色占' },
      { slug: 'juan1/44', title: '八卦类象' },
      { slug: 'juan1/45', title: '八卦万物属类 (长篇)' },
      { slug: 'juan1/46', title: '八卦万物属类 - 坤卦' },
      { slug: 'juan1/47', title: '八卦万物属类 - 震卦' },
      { slug: 'juan1/48', title: '八卦万物属类 - 巽卦' },
      { slug: 'juan1/49', title: '八卦万物属类 - 坎卦' },
      { slug: 'juan1/50', title: '八卦万物属类 - 离卦' },
      { slug: 'juan1/51', title: '八卦万物属类 - 艮卦' },
      { slug: 'juan1/52', title: '八卦万物属类 - 兑卦' },
    ],
    },
  {
      text: '卷二: 体用生克篇',
      collapsed: true,
      chapters: [
        { slug: 'juan2/01', title: '心易占卜玄机' },
      { slug: 'juan2/02', title: '占卜总决' },
      { slug: 'juan2/03', title: '占卜论理决' },
      { slug: 'juan2/04', title: '先天后天论' },
      { slug: 'juan2/05', title: '卦断遗论' },
      { slug: 'juan2/06', title: '八卦心易体用决' },
      { slug: 'juan2/07', title: '体用总决' },
      { slug: 'juan2/08', title: '天时占第一' },
      { slug: 'juan2/09', title: '人事占 (总则)' },
      { slug: 'juan2/10', title: '家室占' },
      { slug: 'juan2/11', title: '屋舍占' },
      { slug: 'juan2/12', title: '婚姻占' },
      { slug: 'juan2/13', title: '生产占' },
      { slug: 'juan2/14', title: '饮食占' },
      { slug: 'juan2/15', title: '求谋占' },
      { slug: 'juan2/16', title: '求名占' },
      { slug: 'juan2/17', title: '求财占' },
      { slug: 'juan2/18', title: '交易占' },
      { slug: 'juan2/19', title: '出行占' },
      { slug: 'juan2/20', title: '行人占' },
      { slug: 'juan2/21', title: '谒见占' },
      { slug: 'juan2/22', title: '失物占' },
      { slug: 'juan2/23', title: '疾病占' },
      { slug: 'juan2/24', title: '官讼占' },
      { slug: 'juan2/25', title: '墓占' },
      { slug: 'juan2/26', title: '《三要灵应篇》序' },
      { slug: 'juan2/27', title: '三要灵验篇 (正文)' },
      { slug: 'juan2/28', title: '十应奥论' },
      { slug: 'juan2/29', title: '十应目论' },
      { slug: 'juan2/30', title: '复明天时之应' },
      { slug: 'juan2/31', title: '复明地理之应' },
      { slug: 'juan2/32', title: '复明人事之应' },
      { slug: 'juan2/33', title: '复明时令之应' },
      { slug: 'juan2/34', title: '复明方卦之应' },
      { slug: 'juan2/35', title: '复明动物之应' },
      { slug: 'juan2/36', title: '复明静物之应' },
      { slug: 'juan2/37', title: '复明言语之应' },
      { slug: 'juan2/38', title: '复明声音之应' },
      { slug: 'juan2/39', title: '复明五色之应' },
      { slug: 'juan2/40', title: '复明写字之应' },
      { slug: 'juan2/41', title: '遗论' },
      { slug: 'juan2/42', title: '体用' },
      { slug: 'juan2/43', title: '体用论' },
      { slug: 'juan2/44', title: '衰旺论' },
      { slug: 'juan2/45', title: '内外论' },
      { slug: 'juan2/46', title: '动静' },
      { slug: 'juan2/47', title: '向背' },
      { slug: 'juan2/48', title: '静占' },
      { slug: 'juan2/49', title: '观物洞玄歌' },
      { slug: 'juan2/50', title: '起卦加数例' },
      { slug: 'juan2/51', title: '屋宅之占诀' },
      { slug: 'juan2/52', title: '器物论' },
    ],
    },
  {
      text: '卷三: 断占总诀篇',
      collapsed: true,
      chapters: [
        { slug: 'juan3/01', title: '八卦方位图' },
      { slug: 'juan3/02', title: '观梅数诀序' },
      { slug: 'juan3/03', title: '八卦定阴阳次序' },
      { slug: 'juan3/04', title: '变卦式八则' },
      { slug: 'juan3/05', title: '占卦诀' },
      { slug: 'juan3/06', title: '体用互变之诀' },
      { slug: 'juan3/07', title: '体用生克之诀' },
      { slug: 'juan3/08', title: '体用衰旺之诀' },
      { slug: 'juan3/09', title: '体用动静之诀' },
      { slug: 'juan3/10', title: '占卜坐端之诀' },
      { slug: 'juan3/11', title: '占卜克应之诀' },
      { slug: 'juan3/12', title: '万物赋' },
      { slug: 'juan3/13', title: '饮食篇' },
      { slug: 'juan3/14', title: '观物玄妙歌决' },
      { slug: 'juan3/15', title: '诸物响应歌' },
      { slug: 'juan3/16', title: '诸卦反对性情' },
      { slug: 'juan3/17', title: '占物类例' },
      { slug: 'juan3/18', title: '又决-体用断物之妙' },
      { slug: 'juan3/19', title: '又诀' },
      { slug: 'juan3/20', title: '物数为体诀' },
      { slug: 'juan3/21', title: '观物看变爻为主' },
      { slug: 'juan3/22', title: '观物克应法' },
      { slug: 'juan3/23', title: '观物趣时诀' },
      { slug: 'juan3/24', title: '观物用易诀' },
      { slug: 'juan3/25', title: '万物戏验' },
      { slug: 'juan3/26', title: '占卜十应诀' },
      { slug: 'juan3/27', title: '正应、互应、变应' },
      { slug: 'juan3/28', title: '方应' },
      { slug: 'juan3/29', title: '日应' },
      { slug: 'juan3/30', title: '刻应' },
      { slug: 'juan3/31', title: '外应' },
      { slug: 'juan3/32', title: '天时应、地理应、人事应' },
      { slug: 'juan3/33', title: '卦应' },
    ],
    },
  {
      text: '卷四: 后天心易篇',
      collapsed: true,
      chapters: [
        { slug: 'juan4/01', title: '序言 (核心思想总纲)' },
      { slug: 'juan4/02', title: '指迷赋 (测字总纲)' },
      { slug: 'juan4/03', title: '玄黄克应歌' },
      { slug: 'juan4/04', title: '玄黄叙 (测字理论溯源)' },
      { slug: 'juan4/05', title: '玄黄歌 (测字心法歌诀)' },
      { slug: 'juan4/06', title: '花押赋 (签名测运)' },
      { slug: 'juan4/07', title: '探玄赋 (万物类象详解)' },
      { slug: 'juan4/08', title: '齐景至理论 (测字心法溯源)' },
      { slug: 'juan4/09', title: '字画经验 (案例集)' },
      { slug: 'juan4/10', title: '十字诗决 (十字吉凶断)' },
      { slug: 'juan4/11', title: '四季水笔' },
      { slug: 'juan4/12', title: '画有阴阳 (笔画阴阳论)' },
      { slug: 'juan4/13', title: '八卦断 (八卦方位笔画论)' },
      { slug: 'juan4/14', title: '相字心易 (测字核心心态)' },
      { slug: 'juan4/15', title: '辨字式 (辨别书写者身份)' },
      { slug: 'juan4/16', title: '笔画筌蹄 (笔画形态吉凶总诀)' },
      { slug: 'juan4/17', title: '奴婢 (特定身份笔迹)' },
      { slug: 'juan4/18', title: '阴人 (女性笔迹)' },
      { slug: 'juan4/19', title: '隔手 (代笔测字)' },
      { slug: 'juan4/20', title: '视势 (观察字的整体态势)' },
      { slug: 'juan4/21', title: '象人 (类比人物)' },
      { slug: 'juan4/22', title: '有所喜 (吉利偏旁)' },
      { slug: 'juan4/23', title: '有所忌 (凶险偏旁)' },
      { slug: 'juan4/24', title: '有所闻 (听觉外应)' },
      { slug: 'juan4/25', title: '有所见 (视觉外应)' },
      { slug: 'juan4/26', title: '以时而言 (按时间/季节断)' },
      { slug: 'juan4/27', title: '以卦而断 (按八卦属性断)' },
      { slug: 'juan4/28', title: '以禽兽而断 (按动物属性断)' },
      { slug: 'juan4/29', title: '取类而言 (按类别/意象断)' },
      { slug: 'juan4/30', title: '以次而言 (按笔顺断)' },
      { slug: 'juan4/31', title: '当添亦添 (添笔会意法)' },
      { slug: 'juan4/32', title: '当减亦减 (减笔会意法)' },
      { slug: 'juan4/33', title: '笔画长短 (笔画变异断)' },
      { slug: 'juan4/34', title: '偏旁侵客 (偏旁形态断)' },
      { slug: 'juan4/35', title: '字画指迷 (常见偏旁部首详解)' },
      { slug: 'juan4/36', title: '问婚姻 (婚姻专题)' },
      { slug: 'juan4/37', title: '官事 (官司专题)' },
      { slug: 'juan4/38', title: '疾病 (疾病专题)' },
      { slug: 'juan4/39', title: '六甲 (生育专题)' },
      { slug: 'juan4/40', title: '求谋 (谋划专题)' },
      { slug: 'juan4/41', title: '行人远信 (寻人/信息专题)' },
      { slug: 'juan4/42', title: '官贵 (求见贵人专题)' },
      { slug: 'juan4/43', title: '失物 (寻物专题)' },
      { slug: 'juan4/44', title: '问寿 (寿命专题)' },
      { slug: 'juan4/45', title: '功名 (功名专题)' },
      { slug: 'juan4/46', title: '行人 (寻人专题之二)' },
      { slug: 'juan4/47', title: '反体 (反向解读法)' },
      { slug: 'juan4/48', title: '六神笔法 (六神笔形识别)' },
      { slug: 'juan4/49', title: '六神主事 (六神功能详解)' },
      { slug: 'juan4/50', title: '青龙形式 (青龙笔形详解)' },
      { slug: 'juan4/51', title: '朱雀形式 (朱雀笔形详解)' },
      { slug: 'juan4/52', title: '勾陈形式 (勾陈笔形详解)' },
      { slug: 'juan4/53', title: '滕蛇形式 (滕蛇笔形详解)' },
      { slug: 'juan4/54', title: '白虎形式 (白虎笔形详解)' },
      { slug: 'juan4/55', title: '玄武形式 (玄武笔形详解)' },
      { slug: 'juan4/56', title: '笔法犯煞 (总论)' },
      { slug: 'juan4/57', title: '玄黄笔法歌 (常见偏旁形态吉凶)' },
      { slug: 'juan4/58', title: '五行体格歌 (五行笔形总论)' },
      { slug: 'juan4/59', title: '时辰断' },
      { slug: 'juan4/60', title: '起六神卦诀 (六神排盘法)' },
      { slug: 'juan4/61', title: '辨别五行歌 (五行笔画识别高级)' },
      { slug: 'juan4/62', title: '五行并歌式 & 辨别六神歌 (总纲)' },
      { slug: 'juan4/63', title: '木式 (木笔详解)' },
      { slug: 'juan4/64', title: '火式 (火笔详解)' },
      { slug: 'juan4/65', title: '土式 (土笔详解)' },
      { slug: 'juan4/66', title: '金式 (金笔详解)' },
      { slug: 'juan4/67', title: '水式 (水笔详解)' },
    ],
    },
  {
      text: '卷五: 五行神煞篇',
      collapsed: true,
      chapters: [
        { slug: 'juan5/01', title: '五行全备' },
      { slug: 'juan5/02', title: '六神形式 (六神形态再定义)' },
      { slug: 'juan5/03', title: '八卦辨 (八卦笔形识别)' },
      { slug: 'juan5/04', title: '贵神 (吉神之一)' },
      { slug: 'juan5/05', title: '喜神' },
      { slug: 'juan5/06', title: '福星' },
      { slug: 'juan5/07', title: '文星' },
      { slug: 'juan5/08', title: '印信' },
      { slug: 'juan5/09', title: '马星' },
      { slug: 'juan5/10', title: '禄神' },
      { slug: 'juan5/11', title: '会神' },
      { slug: 'juan5/12', title: '生神' },
      { slug: 'juan5/13', title: '亡神' },
      { slug: 'juan5/14', title: '家神' },
      { slug: 'juan5/15', title: '官符' },
      { slug: 'juan5/16', title: '文书' },
      { slug: 'juan5/17', title: '灾煞' },
      { slug: 'juan5/18', title: '天狗煞' },
      { slug: 'juan5/19', title: '科名星' },
      { slug: 'juan5/20', title: '丧门' },
      { slug: 'juan5/21', title: '空亡' },
      { slug: 'juan5/22', title: '宜神' },
      { slug: 'juan5/23', title: '忌神' },
      { slug: 'juan5/24', title: '主神' },
      { slug: 'juan5/25', title: '用神' },
      { slug: 'juan5/26', title: '七言作用歌 (测字总诀诗)' },
      { slug: 'juan5/27', title: '比例歌 (高级案例与心法)' },
      { slug: 'juan5/28', title: '西江月 (词牌名，总结)' },
      { slug: 'juan5/29', title: '易理玄微 (易理精微案例)' },
      { slug: 'juan5/30', title: '断扇占 (拆字多解案例)' },
      { slug: 'juan5/31', title: '买香占' },
      { slug: 'juan5/32', title: '古人相字 (经典案例六则)' },
      { slug: 'juan5/33', title: '断富贵贫贱要诀 (笔迹识人总诀)' },
      { slug: 'juan5/34', title: '五行四时旺相休囚例 (五行能量周期表)' },
      { slug: 'juan5/35', title: '五行相生地支 (长生十二宫)' },
      { slug: 'juan5/36', title: '天干地支所属五行' },
      { slug: 'juan5/37', title: '论八卦性情 (卦德)' },
      { slug: 'juan5/38', title: '八卦取象' },
      { slug: 'juan5/39', title: '六十甲子纳-音歌 (宇宙节律的交响诗)' },
      { slug: 'juan5/40', title: '《系辞》八卦类象歌' },
      { slug: 'juan5/41', title: '浑天甲子定局 (六爻纳甲法)' },
      { slug: 'juan5/42', title: '后天时方 (时辰方位吉凶表)' },
      { slug: 'juan5/43', title: '八反格 (反向断事格)' },
      { slug: 'juan5/44', title: '四言独步 (测字总诀)' },
      { slug: 'juan5/45', title: '五言作用歌 (测字心法补充)' },
      { slug: 'juan5/46', title: '别理篇 (测字高级思辨)' },
      { slug: 'juan5/47', title: '六言剖断歌 (心法再总结)' },
      { slug: 'juan5/48', title: '格物篇 (万物类象再发挥)' },
      { slug: 'juan5/49', title: '物理论 (格物篇再总结)' },
      { slug: 'juan5/50', title: '五行六神辨别篇 (理论再总结)' },
      { slug: 'juan5/51', title: '金声章 (万物类象终极赋)' },
    ],
    },
]
  export const meihuaishuSidebar = () => createBookSidebar('《梅花易数》', basePath, chapterGroups)
  