// docs/.vitepress/sidebar/book/eastern/philosophy/daodejing.mts

import { createBookSidebar } from '../../../utils.mts'

// 1. 定义基础路径 (必须与内容路径完全一致)
const basePath = '/eastern/philosophy/pre-qin/daoism/daodejing/'

// 2. 定义章节数据
const chapterGroups = [
  {
    text: '道经 (上篇)',
    collapsed: false,
    chapters: [
      { slug: '01-daofakejing', title: '道可道，非常道' },
      { slug: '02-shanrenzheyu', title: '天下皆知美之为美' },
      { slug: '03-bujuyuzhi', title: '不尚贤，使民不争' },
      { slug: '04-xiangwangweiyu', title: '渊兮似万物之宗' },
      { slug: '05-tiandiyuren', title: '天地不仁，以万物为刍狗' },
      { slug: '06-guchengyue', title: '谷神不死，是谓玄牝' },
      { slug: '07-tianchangdi', title: '天长地久' },
      { slug: '08-shangshanyuehao', title: '上善若水' },
      { slug: '09-chizhuanmanying', title: '持而盈之，不如其已' },
      { slug: '10-zaifenghunyin', title: '载营魄抱一' },
      { slug: '11-shiwuliang', title: '三十辐共一毂' },
      { slug: '12-wuselingren', title: '五色令人目盲' },
      { slug: '13-chongchongruhai', title: '宠辱若惊，贵大患若身' },
      { slug: '14-shiyizhuyu', title: '视之不见，名曰夷' },
      { slug: '15-shanweishi', title: '古之善为士者' },
      { slug: '16-zhizhiyueming', title: '致虚极，守静笃' },
      { slug: '17-taiwenxibei', title: '太上，下知有之' },
      { slug: '18-darenbure', title: '大道废，有仁义' },
      { slug: '19-juerenqiao', title: '绝圣弃智，民利百倍' },
      { slug: '20-duliyudong', title: '唯之与阿，相去几何' },
      { slug: '21-kongdongerxian', title: '孔德之容，惟道是从' },
      { slug: '22-qianchibeiqu', title: '曲则全，枉则直' },
      { slug: '23-xidewuqu', title: '希言自然' },
      { slug: '24-qiyezheng', title: '跂者不立，跨者不行' },
      { slug: '25-youwulun', title: '有物混成，先天地生' },
      { slug: '26-zhongweijib', title: '重为轻根，静为躁君' },
      { slug: '27-shanxingxizhi', title: '善行无辙迹' },
      { slug: '28-zhiruwenan', title: '知其雄，守其雌' },
      { slug: '29-jiangshouyutian', title: '将欲取天下而为之' },
      { slug: '30-wuweishike', title: '以道佐人主者' },
      { slug: '31-bingzhebuxi', title: '夫佳兵者不祥之器' },
      { slug: '32-daochangwuming', title: '道常无名，朴虽小' },
      { slug: '33-zhirenzhiji', title: '知人者智，自知者明' },
      { slug: '34-dadaofanzhi', title: '大道泛兮，其可左右' },
      { slug: '35-zhibuyuexing', title: '执大象，天下往' },
      { slug: '36-jiangyuzhini', title: '将欲歙之，必固张之' },
    ],
  },
  {
    text: '德经 (下篇)',
    collapsed: false,
    chapters: [
      { slug: '37-daochangwuw.png', title: '道常无为而无不为' },
      { slug: '38-shangdexiade', title: '上德不德，是以有德' },
      { slug: '39-guyiwuzheng', title: '昔之得一者' },
      { slug: '40-fanzhewuqu', title: '反者道之动，弱者道之用' },
      { slug: '41-shangshengweidao', title: '上士闻道，勤而行之' },
      { slug: '42-daochuyisanyin', title: '道生一，一生二，二生三' },
      { slug: '43-tianxiazhirou', title: '天下之至柔，驰骋天下之至坚' },
      { slug: '44-mingyuzhongshen', title: '名与身孰亲' },
      { slug: '45-dachengruoyu', title: '大成若缺，其用不弊' },
      { slug: '46-tianshawuzhai', title: '天下有道，却走马以粪' },
      { slug: '47-buxingerzhi', title: '不出户，知天下' },
      { slug: '48-weiwuzhengming', title: '为学日益，为道日损' },
      { slug: '49-shengrenwuxin', title: '圣人无常心，以百姓心为心' },
      { slug: '50-chushensiru', title: '出生入死' },
      { slug: '51-deshuchangzai', title: '道生之，德畜之' },
      { slug: '52-tianxiawusheng', title: '天下有始，以为天下母' },
      { slug: '53-xingyuweidao', title: '使我介然有知，行于大道' },
      { slug: '54-shanjianzhebu', title: '善建者不拔，善抱者不脱' },
      { slug: '55-hanyidezhi', title: '含德之厚，比于赤子' },
      { slug: '56-zhizhewubang', title: '知者不言，言者不知' },
      { slug: '57-yiguzhengyi', title: '以正治国，以奇用兵' },
      { slug: '58-zenfuxiangxi', title: '其政闷闷，其民淳淳' },
      { slug: '59-zhizhiyining', title: '治人事天，莫若啬' },
      { slug: '60-zhidaoyouku', title: '治大国若烹小鲜' },
      { slug: '61-daguxiabao', title: '大国者下流' },
      { slug: '62-daowuzai', title: '道者万物之奥' },
      { slug: '63-weiwudaxiao', title: '为无为，事无事，味无味' },
      { slug: '64-qiuyiran', title: '其安易持，其未兆易谋' },
      { slug: '65-guyiweida', title: '古之善为道者，非以明民' },
      { slug: '66-jiangyishihai', title: '江海所以能为百谷王者' },
      { slug: '67-santobao', title: '天下皆谓我道大，似不肖' },
      { slug: '68-wushizhiyue', title: '善为士者不武' },
      { slug: '69-yanxingweishi', title: '用兵有言：吾不敢为主而为客' },
      { slug: '70-wudaiyizhi', title: '吾言甚易知，甚易行' },
      { slug: '71-zhizhibuyi', title: '知不知，上；不知知，病' },
      { slug: '72-minkongwwei', title: '民不畏威，则大威至' },
      { slug: '73-tianwangwuwang', title: '勇于敢则杀，勇于不敢则活' },
      { slug: '74-minbuwei', title: '民不畏死，奈何以死惧之' },
      { slug: '75-minzhiyiji', title: '民之饥，以其上食税之多' },
      { slug: '76-renshengminsi', title: '人之生也柔弱，其死也坚强' },
      { slug: '77-tianzhiqiuju', title: '天之道，其犹张弓欤' },
      { slug: '78-tianxiashumar', title: '天下莫柔弱于水，而攻坚强者莫之能胜' },
      { slug: '79-heyuewujie', title: '和大怨，必有余怨' },
      { slug: '80-xiaoguoguamin', title: '小国寡民' },
      { slug: '81-xinyanyoubu', title: '信言不美，美言不信' },
    ],
  }
]

// 3. 导出调用辅助函数生成的侧边栏
export const daodejingSidebar = () => createBookSidebar('《道德经》', basePath, chapterGroups)